CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE SEQUENCE HIBERNATE_SEQUENCE AS INTEGER START WITH 6 
CREATE MEMORY TABLE IMAGE(IMAGE_ID BIGINT NOT NULL PRIMARY KEY,TYPE VARCHAR(255),PRODUCT_ID BIGINT)
CREATE MEMORY TABLE PRODUCT(PRODUCT_ID BIGINT NOT NULL PRIMARY KEY,DESCRIPTION VARCHAR(255),NAME VARCHAR(255),PARENT_PRODUCT_ID BIGINT,CONSTRAINT FK1JWUBOK02ABXLA907HJQ2E2 FOREIGN KEY(PARENT_PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID))
ALTER TABLE IMAGE ADD CONSTRAINT FKGPEXTBYEE3UK9U6O2381M7FT1 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
CREATE USER SA PASSWORD ""
GRANT DBA TO SA
SET WRITE_DELAY 10
SET SCHEMA PUBLIC

INSERT INTO PRODUCT VALUES(1,'a simple car','car',NULL)
INSERT INTO PRODUCT VALUES(2,'a ford sport car','Mustang',1)
INSERT INTO PRODUCT VALUES(3,'a ford truck car','VRaptor',1)

INSERT INTO IMAGE VALUES(4,'generic car image',1)
INSERT INTO IMAGE VALUES(5,'sport car image',2)
INSERT INTO IMAGE VALUES(6,'other sport car image',2)